### ISSUE TITLE
Markierbarer Text

### ISSUE THREAD

**Issue by octameter** [epha/kompendium#18]
Da ich regelmässig nach Wirkstoffnamen in Medikamenten suchen muss, wäre es praktisch, wenn Texte auswählbar wären. Das dies mit verschiedenen Designpatterns interferiert liegt auf der Hand, doch eventuell könnte der Wirkstoffname unter dem Markennamen beim Medikamenteneintrag auf der linken Seite markierbar gemacht werden, so dass copy paste des Wirkstoffnamens möglich wird.

**Comment by ephaee** [comment]
Will be fixed with https://github.com/epha/kompendium/issues/20
