### ISSUE TITLE
Suche per URL

### ISSUE THREAD

**Issue by octameter** [epha/kompendium#19]
Es wäre sehr elegant wenn es eine simple API für eine Suchfunktion gäbe, so dass ein übergebener Wert direkt im Suchfeld eine Suche startet. Eine derartige Schnittstelle könnte für die ganze epha Lösung interessant sein.

**Comment by ephaee** [comment]
Implementiert https://kompendium.epha.ch/#/search=Paracetamol/ 
verwirft im moment noch Spezialzeichen wie Umlaute.
