### ISSUE TITLE
Product information not available

### ISSUE THREAD

**Issue by curki** [epha/kompendium#27]
Immer wieder erscheint bei Aufruf (auch merhmalig) eines Produktes die Info "Fachinformation auf Deutsch nicht verfügbar" (zuletzt bei Ubretid). Erst nach refreshen ist die Fachinfo dann ersichtlich. Woran kann das liegen? Schon mehrmals geschehen.

**Comment by ephaee** [comment]
https://kompendium.epha.ch/#/komp:fi,de/gtin:37746/

**Comment by ephaee** [comment]
Can not reproduce :(
