### ISSUE TITLE
character ≤  not shown correctly!

### ISSUE THREAD

**Issue by curki** [epha/kompendium#32]
https://kompendium.epha.ch/#/gtin:62569/
Herzinsuffizienz mit einer linksventrikulären Auswurffraktion £40%

Instead it should be:
Herzinsuffizienz mit einer linksventrikulären Auswurffraktion ≤40%

**Comment by ephaee** [comment]
On windows it happens only on Firefox. Chrome looks correct related https://github.com/epha/kompendium/issues/6

**Comment by curki** [comment]
no, in this case it is Chrome

**Comment by ephaee** [comment]
@curki are you testing on chrome on mac? Because chrome 41 on windows does display the special character corretly. Same for the copy right symbol in #6

**Comment by curki** [comment]
Yes, it is Chrome on mac, version 41.0.2272.104 (64-bit).

**Comment by curki** [comment]
same for the mac of jonas74

**Comment by ephaee** [comment]
All I could find yesterday is that the files are already wrong in download (robot)

I.e. The registered sign (in #6) is a &Ograve; in the .htm file. Why chrome on windows displays the correct registered (R) char is a mistery to me

**Comment by ephaee** [comment]
@Jonas74 the ≤ is ```&pound;``` in the markup

**Comment by Jonas74** [comment]
Source (swissmedic) is wrong. Fixed by replacing character.
