### ISSUE TITLE
Eliquis® (Apixaban) - substance not shown 

### ISSUE THREAD

**Issue by curki** [epha/kompendium#34]
Search for apixaban does not retrieve any result in "Kompendium" (Eliquis®). Substance = "keine Angaben"). One can only search for the product Eliquis®. 
Substance has to be added to allow correct search.

**Comment by ephaee** [comment]
Fixed in the newest version of kompendium. This uses the product and ATC data from download https://kompendium.epha.ch/#/gtins=61549/
