### ISSUE TITLE
Details not properly loaded

### ISSUE THREAD

**Issue by curki** [epha/kompendium#38]
Repetedly, the product details are not shown properly. You have to refresh several times to get the right view.

![bildschirmfoto 2015-05-13 um 12 35 24](https://cloud.githubusercontent.com/assets/5794379/7608757/bdc8c77e-f96c-11e4-9c9b-ea5cd7c0d930.png)

**Comment by ephaee** [comment]
We fixed a bug related to chaing invalidation. This should not happen again. Please reopen if something is not properly loading again.
