### ISSUE TITLE
selecting text problem

### ISSUE THREAD

**Issue by foexenthal** [epha/kompendium#39]
@ephaee 
Wenn man einen einzelnen Satz aus dem Kompendium markieren und kopieren will, wird häufig der gesamte Text markiert, sobald man mit gedrückter Maustaste über den Text fährt.

**Comment by ephaee** [comment]
kannst du mir browser name und version und betriebsystem angeben? passiert das auf fachinformation detail seite oder produkt übersicht?

**Comment by ephaee** [comment]
will be fixed in the next release
