### ISSUE TITLE
Kompendium Search bringt Safari und Chrome unter iOS zum Absturz

### ISSUE THREAD

**Issue by Aragorn71** [epha/kompendium#4]
Kompendium Suche stürzt auf dem iPad mit Retina Display iOS Version 7.1.1 bei der Eingabe von "Pa" ab. Andere Stringfolgen gehen.

**Comment by ephaee** [comment]
Doesn't crash anymore but still not mobile friendly. Seems to be a problem with touch especially on the list-items. Closed in favor of #22
