### ISSUE TITLE
Kompendium; Fachinformation nicht vorhanden

### ISSUE THREAD

**Issue by sschr** [epha/kompendium#41]
Bei gewissen Medikamenten sind Daten wie Packungsgrösse, Preis und ATC-Code vorhanden, die Fachinformation fehlt aber;

Beispiel 1:
Ezetimib Sandoz 10 mg, Tabletten
Zulassung 65100
 - text: "Fachinformation Fachinformation nicht vorhanden"

Beispiel 2:
Gliclazid retard Zentiva 60mg Tabletten
Zulassung 65362
 - text: "Fachinformation Fachinformation nicht vorhanden"

Vielen Dank

**Comment by sschr** [comment]
@ephaee

**Comment by ephaee** [comment]
Es ist in der Tat keine FI für dieses Produkt vorhanden.
