### ISSUE TITLE
Problem with ®

### ISSUE THREAD

**Issue by ephaee** [epha/kompendium#6]
![screen shot 2014-09-22 at 11 15 30](https://cloud.githubusercontent.com/assets/5112286/4353940/367a181c-4239-11e4-9b50-6383480e7ceb.png)

**Comment by ephaee** [comment]
https://kompendium.epha.ch/#/komp:fi,de/gtin:34630/

**Comment by ephaee** [comment]
![screen shot 2015-03-10 at 09 49 10](https://cloud.githubusercontent.com/assets/5112286/6571632/bf9aeb34-c70a-11e4-9218-50ae42e447f8.png)

**Comment by ephaee** [comment]
@jonas74 In the .htm file we have ```&Ograve;```

**Comment by Jonas74** [comment]
Comes directly wrong from source (swissmedic). Fixed by correcting the character.
